export const universalDelegatorAbi = [
  {
    type: "function",
    name: "vault",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "vaultAddress", type: "address" }],
  },
  {
    type: "function",
    name: "getSlot",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint96" }],
    outputs: [
      {
        name: "slot",
        type: "tuple",
        components: [
          { name: "exists", type: "bool" },
          { name: "nextSlot", type: "uint32" },
          { name: "prevSlot", type: "uint32" },
          { name: "totalChildren", type: "uint32" },
          { name: "existChildren", type: "uint32" },
          { name: "firstChild", type: "uint32" },
          { name: "lastChild", type: "uint32" },
          { name: "isShared", type: "bool" },
          { name: "noPlugins", type: "bool" },
          { name: "size", type: "uint128" },
          { name: "prevSum", type: "uint208" },
          { name: "subnetworkOrOperator", type: "bytes32" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getChildrenPending",
    stateMutability: "view",
    inputs: [
      { name: "index", type: "uint96" },
      { name: "duration", type: "uint48" },
    ],
    outputs: [{ name: "pending", type: "uint208" }],
  },
  {
    type: "function",
    name: "getPending",
    stateMutability: "view",
    inputs: [
      { name: "index", type: "uint96" },
      { name: "duration", type: "uint48" },
    ],
    outputs: [{ name: "pending", type: "uint208" }],
  },
  {
    type: "function",
    name: "getBalance",
    stateMutability: "view",
    inputs: [
      { name: "index", type: "uint96" },
      { name: "duration", type: "uint48" },
    ],
    outputs: [{ name: "balance", type: "uint256" }],
  },
  {
    type: "function",
    name: "getAvailable",
    stateMutability: "view",
    inputs: [
      { name: "index", type: "uint96" },
      { name: "duration", type: "uint48" },
    ],
    outputs: [{ name: "available", type: "uint256" }],
  },
  {
    type: "function",
    name: "getAllocated",
    stateMutability: "view",
    inputs: [
      { name: "index", type: "uint96" },
      { name: "duration", type: "uint48" },
    ],
    outputs: [{ name: "allocated", type: "uint256" }],
  },
  {
    type: "function",
    name: "getSlotOfNetwork",
    stateMutability: "view",
    inputs: [{ name: "subnetwork", type: "bytes32" }],
    outputs: [{ name: "index", type: "uint96" }],
  },
  {
    type: "function",
    name: "getSlotOfOperator",
    stateMutability: "view",
    inputs: [
      { name: "parentIndex", type: "uint96" },
      { name: "operator", type: "address" },
    ],
    outputs: [{ name: "index", type: "uint96" }],
  },
  {
    type: "function",
    name: "getNoPluginsSize",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "noPluginsSize", type: "uint256" }],
  },
  {
    type: "function",
    name: "getWithdrawalBuffer",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "withdrawalBuffer", type: "uint256" }],
  },
  {
    type: "function",
    name: "createSlot",
    stateMutability: "nonpayable",
    inputs: [
      { name: "subnetworkOrOperator", type: "bytes32" },
      { name: "parentIndex", type: "uint96" },
      { name: "isShared", type: "bool" },
      { name: "noPlugins", type: "bool" },
      { name: "size", type: "uint128" },
    ],
    outputs: [{ name: "index", type: "uint96" }],
  },
  {
    type: "function",
    name: "setSize",
    stateMutability: "nonpayable",
    inputs: [
      { name: "index", type: "uint96" },
      { name: "size", type: "uint128" },
    ],
    outputs: [{ name: "pending", type: "uint208" }],
  },
  {
    type: "function",
    name: "swapSlots",
    stateMutability: "nonpayable",
    inputs: [
      { name: "index1", type: "uint96" },
      { name: "index2", type: "uint96" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removeSlot",
    stateMutability: "nonpayable",
    inputs: [{ name: "index", type: "uint96" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setWithdrawalBufferSize",
    stateMutability: "nonpayable",
    inputs: [{ name: "newWithdrawalBufferSize", type: "uint128" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setHook",
    stateMutability: "nonpayable",
    inputs: [{ name: "hook", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "multicall",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes[]" }],
    outputs: [],
  },
  { type: "error", name: "AlreadyAssigned", inputs: [] },
  { type: "error", name: "InsufficientHookGas", inputs: [] },
  { type: "error", name: "IsShared", inputs: [] },
  { type: "error", name: "NotAssigned", inputs: [] },
  { type: "error", name: "NotEnoughAvailable", inputs: [] },
  { type: "error", name: "NotEnoughNoPlugins", inputs: [] },
  { type: "error", name: "NotMigrating", inputs: [] },
  { type: "error", name: "NotNetwork", inputs: [] },
  { type: "error", name: "NotNetworkOrMiddleware", inputs: [] },
  { type: "error", name: "NotSameAllocated", inputs: [] },
  { type: "error", name: "NotSameParent", inputs: [] },
  { type: "error", name: "NotSlasher", inputs: [] },
  { type: "error", name: "NotVault", inputs: [] },
  { type: "error", name: "OldVault", inputs: [] },
  { type: "error", name: "PartiallyAllocated", inputs: [] },
  { type: "error", name: "SlotAllocated", inputs: [] },
  { type: "error", name: "SlotNotCreated", inputs: [] },
  { type: "error", name: "TooManyChildren", inputs: [] },
  { type: "error", name: "WrongDepth", inputs: [] },
  { type: "error", name: "WrongOrder", inputs: [] },
] as const;
