# checks that pre-commit hooks pass before allowing to merge a PR

name: pre-commit
on:
  pull_request:
    branches: [main, master, staging, dev, feat/**, fix/**]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ${{ github.event_name == 'push' && 'ci' || 'pr' }}
  ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: bullfrogsec/bullfrog@1831f79cce8ad602eef14d2163873f27081ebfb3 # v0.8.4
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: stable

      - name: Install pre-commit
        run: python -m pip install --upgrade pip pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --color always --show-diff-on-failure
        env:
          SKIP: forge-snapshots,doc
